import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import { ClientProvider } from "./provider";
import "smarthr-ui/smarthr-ui.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
} satisfies Metadata;

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ja">
      <body>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
